config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root to: 'books#root'
  resources :users, only:[:show, :edit, :update, :index, :delete]

  get 'books' => 'book#index'
  get '/books/:id/edit' => 'posts#edit', as: 'edit_post'
  get '/books/:id' => 'books#show', as: 'book1'
  delete '/books/:id' => 'books#destroy', as: 'destroy_book'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

  validates :title, presence: true
  validates :category,  length: { maximum: 200 }
  

end

app/models/book_image.rb
class BookImage < ApplicationRecord

   belongs_to :user
   attachment :image




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :books
  attachment :profile_image
  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }



end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_in_path_for(resource)
  	user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/book_images_controller.rb
class BookImagesController < ApplicationController

   def new
   	@book_image = BookImage.new
   end

   def create
   	@book_image = BookImage.new(book_image_params)
   	@book_image.user_id = current_user.id
   	if @book_image.save
   		redirect_to book_image_path
   else
   		render :new
   	end
end

   def index
   	 @book_images = BookImage.page(params[:page]).reverse_order
   end

   def show
   	@book_image = BookImage.find(params[:id])
   end

   def destroy
   	@book_image = BookImage.find(params)[:id]
   	@book_image.destroy
   	redirect_to book_images_path
   end

private
 def book_image_params
 	params.require(:book_image).permit(:shop_name, :image, :caption, :user_id)
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book, only: [:edit, :update, :destroy]

  def root
  	
  end

  def index
  	@books = Book.all.order(created_at: :desc)
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
    @book1 = Book.new
    # @user = User.find(params[:id])
    # puts @book.user
    if current_user.id != @book.user_id
      @user = User.find(params[:id])
    else
      @user = current_user
    end

  end

  def new
  	@book = Book.new
  end

  def create
  	 book = Book.new(book_params)
     book.user_id = current_user.id
  	 book.save
  	 if book.save
      redirect_to book_path(book.id)
    else
      redirect_to user_path(book.user_id)
    end
  end

  def edit
      @book = Book.find(params[:id])
      @book.user_id = current_user.id
     if @book.save
      else
      redirect_to users_path
    end
  end

  def update
  	book = Book.find(params[:id])
  	book.update(book_params)
  	redirect_to book_path(book)

  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  	end

    def books
    @book = Book.find(params[:id])
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
    end

    def user
    @book = Book.find(params[:id])

    end

   private
   def book_params
   	params.require(:book).permit(:title, :body)
   end

   def correct_book
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to books_path
    end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
     if  @user.id != current_user.id
      redirect_to user_path
     end

  end

  def index
  	@book = Book.new
  	@users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
   end

  def update
  	user = User.find(params[:id])
  	user.update(user_params)
  	puts user.profile_image
  	redirect_to user_path(user.id)

  end

 private
   def user_params
   	params.require(:user).permit(:name, :introduction, :profile_image)
   end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/book_images_helper.rb
module BookImagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="container">
        	
           <h1>Welcome to
              <span class="glyphicon glyphicon-book"></span>
               Bookers!!</h1>
 </div>

app/views/book/index.html.erb
　　<div class="container">
    <div class="row">
      <div class="col-lg-2">
        <h2>User info</h2>
      </div>

           <%= form_for(@book) do |f| %>

      <div class="col-lg-10">
      <table class="table table-striped">
      		<tr><h3>Books</h3>
      			<th>Title</th><th>Opinion</th>
      		</tr>

        <% @books.each do |book| %>
            <section class="book-text">
            	<tr>
              <td class="title"><%= book.title %></td>
              <td class="body"><%= book.body %></td>
             </tr>

            </section>
       <% end %>
      </table>
    </div>
    <h2>New book</h2>
      <h4>Title</h4>
         <%= f.text_field :title %>
       <h4>Opinion</h4>
       <%= f.text_area :body %><br>
       <button class="btn btn-primary">Create book</button>

<% end %>

    </div>
  </div>

app/views/book_images/new.html.erb
<h1>Books</h1>


<h2>New book</h2>
<%= form_for(@book_image) do |f| %>

<h4>Title</h4>
<%= f.text_field :shop_name %>



<h4>Body</h4>
<%= f.text_field :caption %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/_list.html.erb
<div class="col-lg-3">
  <h2>User info</h2>
	<table class="table">
	      <%= attachment_image_tag current_user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %>
	  
     <tr>
      <td>Name</td>
       <td><%= current_user.name %></td>
        </tr>
          <tr>
          <td>introduction</td>
          <td><%= current_user.introduction %></td>
           </tr>
	       </table>
	         <%= link_to edit_user_path(current_user.id) do %>
	         <div class="col-xs-12 glyphicon glyphicon-wrench btn btn-default"></div>
	         <% end %>

			     <%= form_for(book) do |f| %>
			       <h2>New book</h2>
			         <h4>Title</h4>
			         <%= f.text_field :title, class: "col-xs-12" %><br>
			           <h4>Opinion</h4>
			            <%= f.text_area :body, class: "col-xs-12" %>
			             <div class="field create">
	                   <button class="btn btn-primary col-xs-12">Create book</button></div>
                          
	<% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
      <div class="col-md-6 ">
				<h1>Editing Book</h1>
                   <table class="table">
				     <%= form_for(@book) do |f| %>
				        <h4>Title</h4>
				           <%= f.text_field :title, class: "col-xs-12" %>
				            <h4>Body</h4>
				            <%= f.text_area :body, class: "col-xs-12" %><br>
				              </table>
				             <%= link_to 'Update Book', book_path, class: "btn btn-primary btn-md btn-block"  %><br>
			                 	<%= link_to "Show", book_path %> |
				                 <%= link_to "Back", books_path %>
				         <% end %>
	    </div>
      <div class="col-lg-3"></div>
  </div>
</div>

app/views/books/index.html.erb
　　<div class="container">
    <div class="row">

  <%= render 'books/list', book: @book %>

     <div class="col-lg-9">
        <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr></thead> 
                <% @books.each do |book| %>
                <td><%= link_to users_path(book.user_id) do %>
                   <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %>

                  <% end %>
              <td class="title"><%= link_to book.title ,book_path(book.id) %></td>
              <td class="body"><%= book.body %></td></tr>
           <% end %>
          </table>
      </div>





   </div>
</div>

app/views/books/new.html.erb
<h1>Books</h1>


<h2>New book</h2>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>



<h4>Body</h4>
<%= f.text_field :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/root.html.erb
<div class="body">
   <div class="container">
   	 <p class="notice"><%= notice %></p>
	  <div class="row">
        <div class="col-md-offset-3 col-md-6">
           <h1>welcome to
              <span class="glyphicon glyphicon-book"></span>
               <strong>Bookers</strong> !  !</h1>
               <p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers,</strong></p>
             <p class="rrr">you can share and exchange your opinions , inpressions , and emotions</p>


	           <p>about varioius books!</p>
                  <h4 class="headline">
                   <%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>

                   <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></h4>
            </div>
	  </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
<div class="container">
   <div class="row">
<% if @user.id == current_user.id then %>
	 <%= render 'books/list', book:@book1 %>
 <% else %>

<div class="col-lg-3">
  <h2>User info</h2>
	<table class="table">
	      <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %>
     <tr>
      <td>Name</td>
       <td><%= @user.name %></td>
        </tr>
          <tr>
          <td>introduction</td>
          <td><%= @user.introduction %></td>
           </tr>
	       </table>
	         <%= link_to edit_user_path(@user.id) do %>
	         <div class="col-xs-12 glyphicon glyphicon-wrench btn btn-default"></div>
	         <% end %>

			     <%= form_for(@book1) do |f| %>
			       <h2>New book</h2>
			         <h4>Title</h4>
			         <%= f.text_field :title, class: "col-xs-12" %><br>
			           <h4>Opinion</h4>
			            <%= f.text_area :body, class: "col-xs-12" %>
			             <div class="field create">
	                   <button class="btn btn-primary col-xs-12">Create book</button></div>
	               <% end %>
  </div>
<% end %>

    <h2>Book detail</h2>
         <div class="col-lg-9">
             <table class="table">
             	<tr>
                  <td><%= link_to user_path(@book.user.id) do %>
                   <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %><br>
                 <%= @book.user.name  %>
                 <% end %></td>

               <td class="title"><%= @book.title %></td>
              <td class="body"><%= @book.body %></td>
              <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %></td>
              <% end %>
                </tr>
             </table>
    </div>
   </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header style= "background-color: black">
    <div class="container">
     <div class="row" style= "color: white;">
        <div class="col-lg-1"></div>
        <div class="col-xs-12">
          <div id="slidemenu">
            <h4 class="pull-left">Bookers</h4>
            <ul class="nav navbar-nav navbar-right test" >
              <% if user_signed_in? %>
                <li class="" >
                  <%= link_to "Top", user_path(current_user), class: "glyphicon glyphicon-home nav-color" %>
                </li>
                <li class="">
                  <%= link_to 'Users', users_path, class: "glyphicon glyphicon-user nav-color" %>
                </li>
                <li class="">
                  <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book nav-color" %>
                </li>
                <li class="">
                   <%= link_to 'logout', destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out nav-color" %>
                </li>
              <% else %>
                <li class="">
                  <%= link_to 'Home', root_path, class: "glyphicon glyphicon-home nav-color test" %>
                </li>
                <li class="">
                  <%= link_to 'About', about_index_path, class: "glyphicon glyphicon-link nav-color" %>
                </li>

                <li class="">
                  <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit nav-color" %>
                </li>
                <li class="">
                  <%= link_to "log in", new_user_session_path, class: "glyphicon glyphicon-log-in nav-color" %>
                </li>
              <% end %>
            </ul>
           </div>
        </div>
        <div class="col-lg-1"></div>
     </div> 
    </div>
  </header>

    <%= yield %>
        </body>

    
    <footer>
      <div class="container">
        <div class="row">
         <div class="col-xs-3 col-xs-offset-9">
        CopyRight Infratop.inc
         </div>
        </div>
      </div>
    </footer>


</html>

app/views/users/edit.html.erb
<div class="container">
   <div class="row">
          <h2>User info</h2>
              <%= form_for(@user) do |f| %>
            <div class="form-group has-icon">
                <label>Name</label>
                <%= f.text_field :name, autofocus: true, id:"name" %>

                <div class="field"><label>Image</label>
                <%= f.attachment_field :profile_image %></div>

            <label>Introduction</label>
                <%= f.text_area :introduction, autofocus: true, id:"introduction" %>
            </div>
            <div class= "actions">
            <%= f.submit "Update User" %></div>
        <% end %>

  </div>
 </div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
	 <div class="row">

	  <%= render 'books/list', book: @book %>

	  <div class="col-lg-9">
	      <h2>Users</h2>
	         <table class="table">
	            <thead>
	            <tr>
	             <th>image</th>
	             <th>name</th>
	            </tr> 
	            </thead>
	                <% @users.each do |a| %>
	                 	<tr>
	              		<td><%= attachment_image_tag a, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %></td>
	                      <td><%= a.name %></td>
	                      <td><%= link_to "show",  user_path(a.id) %></td>
	                   </tr>
	                  </thead>    
	           <% end %>
	          </table>
	    </div>
	 </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
　　<div class="container">
	<p class="notice"><%= notice %></p>
      <div class="row">
<% if @user.id == current_user.id then %>
 <%= render 'books/list', book:@book %>
 <% else %>
<div class="col-lg-3">
  <h2>User info</h2>
	<table class="table">
	      <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %>
	  
     <tr>
      <td>Name</td>
       <td><%= @user.name %></td>
        </tr>
          <tr>
          <td>introduction</td>
          <td><%= @user.introduction %></td>
           </tr>
	       </table>
	         <%= link_to edit_user_path(@user.id) do %>
	         <div class="col-xs-12 glyphicon glyphicon-wrench btn btn-default"></div>
	         <% end %>

			     <%= form_for(@book) do |f| %>
			       <h2>New book</h2>
			         <h4>Title</h4>
			         <%= f.text_field :title, class: "col-xs-12" %><br>
			           <h4>Opinion</h4>
			            <%= f.text_area :body, class: "col-xs-12" %>
			             <div class="field create">
	                   <button class="btn btn-primary col-xs-12">Create book</button></div>
	<% end %>
 </div>
<% end %>

	        <div class="col-lg-9">
	      	   <h2>Books</h2>
	              <table class="table">
	      		<thead><tr>
	      			<th></th><th>Title</th><th>Opinion</th>
	      		</tr></thead>
	             <% @books.each do |book| %>
	            <section class="book-text">
	              <tr>
	             <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "zz.jpg" %></td>
	              <td class="title"><%= link_to book.title ,book_path(book.id) %></td>
	              <td class="body"><%= book.body %></td>
		           </tr>
	            </section>
	             <% end %>
	          </table>
             </div>
     </div>
  </div>
</div>　　